const DISCOUNT = Object.freeze({
  PREMIUM_RATE: 0.1,
  REGULAR_RATE: 0.05,
  REGULAR_MIN_SUBTOTAL: 100,
  MAX_RATE: 0.3,
});

const COUPON = Object.freeze({
  CAFE10_DISCOUNT_RATE: 0.1,
  BEMVINDO_FIXED_DISCOUNT: 5,
});

const DELIVERY = Object.freeze({
  BASE_FEE: 7,
  FREE_DELIVERY_MIN_SUBTOTAL: 50,
  INCLUDED_DISTANCE_KM: 3,
  FEE_PER_EXTRA_KM: 1.5,
  MAX_DISTANCE_KM: 10,
});

const ORDER_LIMITS = Object.freeze({
  MAX_OPEN_ORDERS_PER_CUSTOMER: 3,
  MAX_QUANTITY_PER_PRODUCT: 10,
  MAX_DISTINCT_ITEMS: 15,
});

module.exports = { DISCOUNT, COUPON, DELIVERY, ORDER_LIMITS };
