const DISCOUNT = Object.freeze({
  PREMIUM_RATE: 0.1,
  REGULAR_RATE: 0.05,
  REGULAR_MIN_SUBTOTAL: 100,
  MAX_RATE: 0.3,
});

const COUPON = Object.freeze({
  CAFE10_DISCOUNT_RATE: 0.1,
  BEMVINDO_FIXED_DISCOUNT: 5,
});

const DELIVERY = Object.freeze({
  BASE_FEE: 7,
  FREE_DELIVERY_MIN_SUBTOTAL: 50,
  INCLUDED_DISTANCE_KM: 3,
  FEE_PER_EXTRA_KM: 1.5,
  MAX_DISTANCE_KM: 10,
});

const ORDER_LIMITS = Object.freeze({
  MAX_OPEN_ORDERS_PER_CUSTOMER: 3,
  MAX_QUANTITY_PER_PRODUCT: 10,
  MAX_DISTINCT_ITEMS: 15,
});

const PAYMENT = Object.freeze({
  PIX_DISCOUNT_RATE: 0.05,
  PIX_KEY: 'pagamentos@cafeteria.com',
  MIN_INSTALLMENTS: 1,
  MAX_INSTALLMENTS: 12,
  INTEREST_FREE_INSTALLMENTS: 3,
  INTEREST_RATE_PER_EXTRA_INSTALLMENT: 0.02,
  MIN_INSTALLMENT_VALUE: 10,
  MAX_CHANGE_FOR_DELIVERY: 50,
});

const CARD = Object.freeze({
  NUMBER_LENGTH: 16,
  VISIBLE_DIGITS: 4,
});

const LOYALTY = Object.freeze({
  POINTS_PER_REAL: 1,
  PREMIUM_POINTS_MULTIPLIER: 2,
  PREMIUM_UPGRADE_POINTS: 200,
});

const CANCELLATION = Object.freeze({
  PREPARING_REFUND_RATE: 0.5,
});

const PRODUCT_RULES = Object.freeze({
  MAX_PRICE: 500,
  MAX_STOCK: 200,
});

const CUSTOMER_RULES = Object.freeze({
  MIN_NAME_LENGTH: 3,
});

module.exports = {
  DISCOUNT,
  COUPON,
  DELIVERY,
  ORDER_LIMITS,
  PAYMENT,
  CARD,
  LOYALTY,
  CANCELLATION,
  PRODUCT_RULES,
  CUSTOMER_RULES,
};
